Messaging
Desar14/LearnNet_MessageProcessor pull request #1
Opened 2023-11-20 22:54 UTC by Desar14

2023-11-21 10:05 UTC, KirylPrykhodzka requested changes

2023-11-21 10:05 UTC, KirylPrykhodzka commented on ProductUpdateModel.cs
> +    public class ItemImageModel
one class per file please

2023-11-21 10:05 UTC, KirylPrykhodzka commented on Program.cs
> +        static string CartingServiceBaseUrl = "https://localhost:7268/api/v1/CartItems";
make use of appsettings

2023-11-21 10:05 UTC, KirylPrykhodzka commented on Program.cs
> +                    "learningnet.servicebus.windows.net",
make use of appsettings

2023-11-21 10:05 UTC, KirylPrykhodzka commented on Program.cs
> +            async Task MessageHandler(ProcessMessageEventArgs args)
please specify access scope explicitly (add private keyword)

2023-11-21 10:05 UTC, KirylPrykhodzka commented on Program.cs
> +                if (response.StatusCode >= System.Net.HttpStatusCode.BadRequest)
Does not make too much sense to me to handle 5xx and 4xx status codes differently.
Let's discuss it at our meeting

2023-11-21 13:10 UTC, Desar14 commented on Program.cs
> +                if (response.StatusCode >= System.Net.HttpStatusCode.BadRequest)
make same handling

2023-11-22 08:03 UTC, KirylPrykhodzka approved these changes

2023-11-22 10:08 UTC, merged